// Code generated by running "go generate" in golang.org/x/text. DO NOT EDIT.

package catalog

import (
	"golang.org/x/text/language"
	"golang.org/x/text/message"
	"golang.org/x/text/message/catalog"
)

type dictionary struct {
	index []uint32
	data  string
}

func (d *dictionary) Lookup(key string) (data string, ok bool) {
	p, ok := messageKeyToIndex[key]
	if !ok {
		return "", false
	}
	start, end := d.index[p], d.index[p+1]
	if start == end {
		return "", false
	}
	return d.data[start:end], true
}

func init() {
	dict := map[string]catalog.Dictionary{
		"en": &dictionary{index: enIndex, data: enData},
		"fr": &dictionary{index: frIndex, data: frData},
	}
	fallback := language.MustParse("en")
	cat, err := catalog.NewFromMap(dict, catalog.Fallback(fallback))
	if err != nil {
		panic(err)
	}
	message.DefaultCatalog = cat
}

var messageKeyToIndex = map[string]int{
	"1 day":                  43,
	"1 hour":                 42,
	"1 month":                45,
	"1 week":                 44,
	"1 year":                 46,
	"10 minutes":             41,
	"400 Bad Request":        0,
	"404 Not Found":          1,
	"405 Method Not Allowed": 2,
	"5 minutes":              40,
	"All texts added via OpenGoPaste are encrypted in AES 256 by the browser before being sent to the server so that only the author of these lines and the recipient(s) can access the content.": 9,
	"Alternative official logo source code":     19,
	"As for GoFast, it is better to be hidden!": 38,
	"Code is under license":                     14,
	"Content":                                   32,
	"Copy link and send it.":                    27,
	"Create a new paste":                        37,
	"Development and design":                    11,
	"Download original work":                    22,
	"Expire in":                                 29,
	"Fail to read file %s : %s":                 51,
	"Format":                                    30,
	"Icon and logo":                             12,
	"Invalid paste content":                     4,
	"Link has been copied !":                    28,
	"Logos are under license":                   15,
	"Maximum read allowed":                      31,
	"Official logo source code":                 18,
	"OpenGoPaste build by:":                     10,
	"OpenGoPaste is free software that allows you to securely put notes, code or texts online for sharing.": 8,
	"OpenGoPaste is free software.": 13,
	"Save":                          33,
	"Show source code":              16,
	"Software source code":          17,
	"This message can be viewed again §nBAvailableRead§ times or up to §dateAvailable§ at §hourAvailable§.": 34,
	"This message can be viewed up to §dateAvailable§ at §hourAvailable§.":                                  35,
	"This message is available for the last time. You will not be able to consult it later.":                36,
	"This paste doesn't exist":               50,
	"This paste doesn't exist or is expired": 52,
	"Unofficial logo source code":            20,
	"and finally continue by":                26,
	"code":                                   48,
	"is a text and source code management service. The data sent by this service are known only by you and the recipient (s) of the link because they are encrypted and decrypted by the browser. At no time does the service know the data that is sent.": 39,
	"markdown":                              49,
	"max_read value must be a positive int": 5,
	"modified by":                           25,
	"of":                                    24,
	"original creation":                     23,
	"text":                                  47,
	"this max_time value is not allowed":    6,
	"this paste is not found":               3,
	"this type value is not allowed":        7,
	"work derived from an":                  21,
}

var enIndex = []uint32{ // 54 elements
	// Entry 0 - 1F
	0x00000000, 0x00000010, 0x0000001e, 0x00000035,
	0x0000004d, 0x00000063, 0x00000089, 0x000000ac,
	0x000000cb, 0x00000131, 0x000001ed, 0x00000203,
	0x0000021a, 0x00000228, 0x00000246, 0x0000025c,
	0x00000274, 0x00000285, 0x0000029a, 0x000002b4,
	0x000002da, 0x000002f6, 0x0000030b, 0x00000322,
	0x00000334, 0x00000337, 0x00000343, 0x0000035b,
	0x00000372, 0x00000389, 0x00000393, 0x0000039a,
	// Entry 20 - 3F
	0x000003af, 0x000003b7, 0x000003bc, 0x00000428,
	0x00000471, 0x000004c8, 0x000004db, 0x00000505,
	0x000005fa, 0x00000604, 0x0000060f, 0x00000616,
	0x0000061c, 0x00000623, 0x0000062b, 0x00000632,
	0x00000637, 0x0000063c, 0x00000645, 0x0000065e,
	0x0000067e, 0x000006a5,
} // Size: 240 bytes

const enData string = "" + // Size: 1701 bytes
	"\x02400 Bad Request\x02404 Not Found\x02405 Method Not Allowed\x02this p" +
	"aste is not found\x02Invalid paste content\x02max_read value must be a p" +
	"ositive int\x02this max_time value is not allowed\x02this type value is " +
	"not allowed\x02OpenGoPaste is free software that allows you to securely " +
	"put notes, code or texts online for sharing.\x02All texts added via Open" +
	"GoPaste are encrypted in AES 256 by the browser before being sent to the" +
	" server so that only the author of these lines and the recipient(s) can " +
	"access the content.\x02OpenGoPaste build by:\x02Development and design" +
	"\x02Icon and logo\x02OpenGoPaste is free software.\x02Code is under lice" +
	"nse\x02Logos are under license\x02Show source code\x02Software source co" +
	"de\x02Official logo source code\x02Alternative official logo source code" +
	"\x02Unofficial logo source code\x02work derived from an\x02Download orig" +
	"inal work\x02original creation\x02of\x02modified by\x02and finally conti" +
	"nue by\x02Copy link and send it.\x02Link has been copied !\x02Expire in" +
	"\x02Format\x02Maximum read allowed\x02Content\x02Save\x02This message ca" +
	"n be viewed again §nBAvailableRead§ times or up to §dateAvailable§ at §h" +
	"ourAvailable§.\x02This message can be viewed up to §dateAvailable§ at §h" +
	"ourAvailable§.\x02This message is available for the last time. You will " +
	"not be able to consult it later.\x02Create a new paste\x02As for GoFast," +
	" it is better to be hidden!\x02is a text and source code management serv" +
	"ice. The data sent by this service are known only by you and the recipie" +
	"nt (s) of the link because they are encrypted and decrypted by the brows" +
	"er. At no time does the service know the data that is sent.\x025 minutes" +
	"\x0210 minutes\x021 hour\x021 day\x021 week\x021 month\x021 year\x02text" +
	"\x02code\x02markdown\x02This paste doesn't exist\x02Fail to read file %[" +
	"1]s : %[2]s\x02This paste doesn't exist or is expired"

var frIndex = []uint32{ // 54 elements
	// Entry 0 - 1F
	0x00000000, 0x00000016, 0x0000002c, 0x00000048,
	0x00000069, 0x0000007a, 0x000000ad, 0x000000d8,
	0x000000ff, 0x0000018b, 0x00000269, 0x0000028d,
	0x000002a6, 0x000002b5, 0x000002d8, 0x000002f1,
	0x0000030e, 0x00000322, 0x0000033a, 0x00000352,
	0x00000371, 0x0000038a, 0x000003a1, 0x000003c6,
	0x000003da, 0x000003dd, 0x000003ea, 0x000003fe,
	0x0000041c, 0x00000435, 0x00000441, 0x00000448,
	// Entry 20 - 3F
	0x00000462, 0x0000046a, 0x00000476, 0x000004ec,
	0x0000053f, 0x000005a1, 0x000005b9, 0x000005f4,
	0x00000723, 0x0000072d, 0x00000738, 0x00000740,
	0x00000747, 0x00000751, 0x00000758, 0x0000075d,
	0x00000763, 0x00000768, 0x00000771, 0x00000789,
	0x000007b9, 0x000007de,
} // Size: 240 bytes

const frData string = "" + // Size: 2014 bytes
	"\x02400 Mauvaise requête\x02404 Page non trouvée\x02405 Méthode non auto" +
	"risée\x02Ce contenu n'a pas été trouvé\x02Contenu invalide\x02La valeur " +
	"de max_read doit être un entier positif\x02La valeur de max_time n'est p" +
	"as autorisée\x02La valeur du type n'est pas autorisée\x02OpenGoPaste est" +
	" un logiciel libre permettant mettre en ligne de manière sécurisée des n" +
	"otes, du code ou des textes afin de les partager.\x02L'ensemble des text" +
	"es ajoutés via OpenGoPaste sont chiffrés en AES 256 par le navigateur av" +
	"ant d'être envoyés au serveur afin que seul l'auteur de ces lignes et le" +
	" ou les destinataires ne puissent accéder au contenu.\x02OpenGoPaste a é" +
	"té réalisé par :\x02Développement et design\x02Icône et logo\x02OpenGoPa" +
	"ste est un logiciel libre.\x02Le code est sous licence\x02Les logos sont" +
	" sous licence \x02Voir le code source\x02Code source du logiciel\x02Sour" +
	"ce du logo officiel\x02Source du second logo officiel\x02Source du logo " +
	"officieux\x02œuvre dérivée d'une\x02Télécharger la création originale" +
	"\x02création originale\x02de\x02modifié par\x02et enfin repris par\x02Co" +
	"pier le lien et envoyer le.\x02Le lien a été copié !\x02Expire dans\x02F" +
	"ormat\x02Nombre de lecture maximum\x02Contenu\x02Enregistrer\x02Ce messa" +
	"ge pourra être consulté encore §nbAvailableRead§ fois ou jusqu'au §dateA" +
	"vailable§ à §hourAvailable§.\x02Ce message pourra être consulté jusqu'au" +
	" §dateAvailable§ à §hourAvailable§.\x02Ce message est disponible pour la" +
	" dernière fois. Vous ne pourrez plus le consulter par la suite.\x02Créer" +
	" un nouveau paste\x02Comme pour le GoFast, il est préférable d'être cach" +
	"é !\x02est un service de gestion d'extraits de texte et de code source." +
	" Les données envoyées par ce service ne sont connues que par vous seul e" +
	"t le(s) destinataire(s) du lien car elles sont chiffrées et déchiffrées " +
	"par le navigateur. À aucun moment le service ne connait les données qui " +
	"sont envoyées.\x025 minutes\x0210 minutes\x021 heure\x021 jour\x021 sema" +
	"ine\x021 mois\x021 an\x02Texte\x02Code\x02Markdown\x02Ce contenu n'exist" +
	"e pas\x02Erreur dans la lecture du fichier %[1]s : %[2]s\x02Ce contenu n" +
	"'existe pas ou a expiré"

	// Total table size 4195 bytes (4KiB); checksum: 21CFDA47
